name: Second

on: [push, pull_request]

jobs:
  job1:
      name: First Job
      runs-on: ubuntu-latest
      steps:
        - name: task1
          uses: actions/checkout
          run: |
                pwd
                ls -lrt
        - name: task2
          run: env | sort
  job2:
      name: Second Job
      runs-on: windows-latest
      steps:
        - name: task3
          uses: actions/checkout
        - name: task4
          run: "Get-ChildItem Env:"
                
